services:
  influxdb:
    container_name: db
    image: influxdb:latest
    ports:
      - '8086:8086'
    restart: unless-stopped
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    networks:
      - default
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=uni
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  fetcher:
    depends_on:
      - influxdb
    networks:
      - default
    environment:
      - INFLUX_ORG=admin
      - INFLUX_BUCKET=uni
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
    build:
      context: .
      dockerfile: fetcher/DOCKERFILE
    restart: unless-stopped

networks:
  default:
volumes:
  influxdb-storage:
